services:
  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network-product

  nginx:
    build:
      context: ./frontend
      dockerfile: ./dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - network-product

  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-my_database}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network-product

volumes:
  db_data:

networks:
  network-product:
    driver: bridge